#!/bin/bash
#Shell script to find all image files in a specified folder
  echo "Enter desired folder location:"
  read pathfind
#variable pathfind will have the pathname to desired folder
  cd $pathfind
  ls -al | grep -i ".jpg"